//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS
{
    public partial class ManufactureM
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;
        protected global::System.Web.UI.WebControls.LinkButton lbtnTopBack;
        protected global::System.Web.UI.WebControls.LinkButton lbtnTopHome;
        protected global::System.Web.UI.WebControls.Label lblUsername;
        protected global::System.Web.UI.WebControls.LinkButton lbtnLogOut;
        protected global::System.Web.UI.UpdatePanel upMain;

        protected global::System.Web.UI.WebControls.Label lblPrompt;
        protected global::System.Web.UI.WebControls.Panel pnlScan;
        protected global::System.Web.UI.WebControls.TextBox txtScan;
        protected global::System.Web.UI.WebControls.LinkButton lbtnLoadDoc;
        protected global::System.Web.UI.WebControls.LinkButton lbtnClearScan;
        protected global::System.Web.UI.WebControls.Label lblFeedback;

        protected global::System.Web.UI.WebControls.Panel pnlWO;
        protected global::System.Web.UI.WebControls.Label lblWONum;
        protected global::System.Web.UI.WebControls.Label lblOutItem;
        protected global::System.Web.UI.WebControls.Label lblOutUnit;
        protected global::System.Web.UI.WebControls.Label lblOutDescr;
        protected global::System.Web.UI.WebControls.Label lblRemaining;
        protected global::System.Web.UI.WebControls.Repeater rptBom;

        protected global::System.Web.UI.WebControls.Panel pnlMake;
        protected global::System.Web.UI.WebControls.DropDownList ddlStore;
        protected global::System.Web.UI.WebControls.DropDownList ddlToStore;
        protected global::System.Web.UI.WebControls.TextBox txtQty;
        protected global::System.Web.UI.WebControls.LinkButton lbtnMakeHere;
        protected global::System.Web.UI.WebControls.LinkButton lbtnMakeMove;

        protected global::System.Web.UI.WebControls.LinkButton lbtnRestart;

        protected global::System.Web.UI.WebControls.Panel pnlDone;
        protected global::System.Web.UI.WebControls.Label lblDoneCount;
        protected global::System.Web.UI.WebControls.Repeater rptDone;
    }
}
