//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS
{


    public partial class QuickMoveM
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// UpdateProgress1 control.
        /// </summary>
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;

        /// <summary>
        /// lbtnTopBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnTopBack;

        /// <summary>
        /// lbtnTopHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnTopHome;

        /// <summary>
        /// lblUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsername;

        /// <summary>
        /// lbtnLogOut control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnLogOut;

        /// <summary>
        /// upMain control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel upMain;

        /// <summary>
        /// hfActionToken control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfActionToken;

        /// <summary>
        /// lblSteps control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal lblSteps;

        /// <summary>
        /// lblPrompt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPrompt;

        /// <summary>
        /// pnlScanBar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlScanBar;

        /// <summary>
        /// txtScan control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtScan;

        /// <summary>
        /// lbtnClearScan control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnClearScan;

        /// <summary>
        /// tap-mode controls.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTapMode;
        protected global::System.Web.UI.WebControls.DropDownList ddFromStore;
        protected global::System.Web.UI.WebControls.Panel pnlContents;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.LinkButton lbtnClearSearch;
        protected global::System.Web.UI.WebControls.Repeater rptContents;
        protected global::System.Web.UI.WebControls.Label lblNoContents;
        protected global::System.Web.UI.WebControls.Panel pnlToStore;
        protected global::System.Web.UI.WebControls.DropDownList ddToStore;

        /// <summary>
        /// lblFeedback control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFeedback;

        /// <summary>
        /// pnlOutDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOutDetail;

        /// <summary>
        /// lblOutItem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOutItem;

        /// <summary>
        /// lblOutUnit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOutUnit;

        /// <summary>
        /// lblOutDescr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOutDescr;

        /// <summary>
        /// ddLot control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddLot;

        /// <summary>
        /// txtQty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQty;

        /// <summary>
        /// lblAvail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAvail;

        /// <summary>
        /// lbtnConfirmOut control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnConfirmOut;

        /// <summary>
        /// pnlSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSummary;

        /// <summary>
        /// lblSumFrom control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSumFrom;

        /// <summary>
        /// lblSumDest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSumDest;

        /// <summary>
        /// lblSumQty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSumQty;

        /// <summary>
        /// lblSumItem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSumItem;

        /// <summary>
        /// lbtnFinish control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnFinish;

        /// <summary>
        /// lbtnRestart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnRestart;

        /// <summary>
        /// pnlDone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDone;

        /// <summary>
        /// lblDoneCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDoneCount;

        /// <summary>
        /// rptDone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptDone;
    }
}
