//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS
{
    public partial class StockCountsM
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;
        protected global::System.Web.UI.WebControls.LinkButton lbtnBack;
        protected global::System.Web.UI.WebControls.LinkButton lbtnHome;
        protected global::System.Web.UI.WebControls.Label lblUsername;
        protected global::System.Web.UI.WebControls.LinkButton lbtnLogOut;
        protected global::System.Web.UI.UpdatePanel upMain;
        protected global::System.Web.UI.WebControls.Panel pnlCountSelect;
        protected global::System.Web.UI.WebControls.DropDownList ddCounts;
        protected global::System.Web.UI.WebControls.LinkButton lbtnLoadCount;
        protected global::System.Web.UI.WebControls.CheckBox chkShowClosed;
        protected global::System.Web.UI.WebControls.Panel pnlCountHeader;
        protected global::System.Web.UI.WebControls.Label lblCountRef;
        protected global::System.Web.UI.WebControls.Label lblCountStatus;
        protected global::System.Web.UI.WebControls.Label lblCountDate;
        protected global::System.Web.UI.WebControls.Label lblCreatedBy;
        protected global::System.Web.UI.WebControls.Label lblLineCount;
        protected global::System.Web.UI.WebControls.DropDownList ddStore;
        protected global::System.Web.UI.WebControls.LinkButton lbtnStartCounting;
    }
}
