//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS
{
    public partial class StockCountLineM
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;
        protected global::System.Web.UI.WebControls.LinkButton lbtnBack;
        protected global::System.Web.UI.WebControls.LinkButton lbtnHome;
        protected global::System.Web.UI.WebControls.Label lblCountRefTop;
        protected global::System.Web.UI.WebControls.Label lblStoreBadge;
        protected global::System.Web.UI.WebControls.Label lblUsername;
        protected global::System.Web.UI.WebControls.LinkButton lbtnLogOut;
        protected global::System.Web.UI.UpdatePanel upMain;
        protected global::System.Web.UI.WebControls.Label lblCountRef;
        protected global::System.Web.UI.WebControls.Label lblCountStatus;
        protected global::System.Web.UI.WebControls.Label lblCountDate;
        protected global::System.Web.UI.WebControls.Label lblStoreName;
        protected global::System.Web.UI.WebControls.Label lblLineCount;
        protected global::System.Web.UI.WebControls.Panel pnlScanBar;
        protected global::System.Web.UI.WebControls.TextBox txtBarcode;
        protected global::System.Web.UI.WebControls.LinkButton lbtnClearScan;
        protected global::System.Web.UI.WebControls.Label lblScanFeedback;
        protected global::System.Web.UI.WebControls.Panel pnlCalculator;
        protected global::System.Web.UI.WebControls.Label lblCalcItemCode;
        protected global::System.Web.UI.WebControls.Label lblCalcItemDesc;
        protected global::System.Web.UI.WebControls.Label lblCalcRound;
        protected global::System.Web.UI.WebControls.Label lblCalcQtyHint;
        protected global::System.Web.UI.WebControls.LinkButton lbtnCalcCancel;
        protected global::System.Web.UI.WebControls.LinkButton lbtnCalcSave;
        protected global::System.Web.UI.WebControls.HiddenField hfCalcCtLineID;
        protected global::System.Web.UI.WebControls.HiddenField hfCalcExpression;
        protected global::System.Web.UI.WebControls.HiddenField hfCalcTotal;
        protected global::System.Web.UI.WebControls.HiddenField hfCalcInitQty;
        protected global::System.Web.UI.WebControls.HiddenField hfCalcRoundText;
        protected global::System.Web.UI.WebControls.Panel pnlCloseOff;
        protected global::System.Web.UI.WebControls.Label lblCloseOffError;
        protected global::System.Web.UI.WebControls.LinkButton lbtnCancelCloseOff;
        protected global::System.Web.UI.WebControls.LinkButton lbtnConfirmCloseOff;
        protected global::System.Web.UI.WebControls.DropDownList ddCategory;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.LinkButton lbtnSearch;
        protected global::System.Web.UI.WebControls.Repeater rptLines;
        protected global::System.Web.UI.WebControls.Label lblEmpty;
        protected global::System.Web.UI.WebControls.LinkButton lbtnCloseOff;
    }
}
