//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsMaster
    {
        public int AcctID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> AccountID { get; set; }
        public string AccountName { get; set; }
        public string AccountDescr { get; set; }
        public Nullable<bool> JCUse { get; set; }
        public Nullable<bool> WOUse { get; set; }
        public Nullable<bool> PSUse { get; set; }
        public Nullable<long> AcctCategID { get; set; }
        public string AcctCategDescr { get; set; }
        public Nullable<decimal> AcctBalance { get; set; }
        public Nullable<long> AcctDefTaxTypeID { get; set; }
        public Nullable<decimal> AcctdefTaxTypePerc { get; set; }
        public bool AccountAddCosts { get; set; }
        public bool AccountAddCostsContra { get; set; }
    }
}
