//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvCostChangeLog
    {
        public int adtID { get; set; }
        public int CompanyID { get; set; }
        public string ItemID { get; set; }
        public Nullable<System.DateTime> CostChangeDate { get; set; }
        public Nullable<int> CostChangeBy { get; set; }
        public Nullable<decimal> SageQOHBefore { get; set; }
        public Nullable<decimal> SageAvUnitCostBefore { get; set; }
        public Nullable<decimal> SageTotValueBefore { get; set; }
        public Nullable<decimal> QtyImported { get; set; }
        public Nullable<decimal> QtyUnitPrice { get; set; }
        public Nullable<decimal> QtyUnitAddCosts { get; set; }
        public Nullable<decimal> QtyImportTotalValue { get; set; }
        public Nullable<decimal> SageQOHAfter { get; set; }
        public Nullable<decimal> SageTotValueAfter { get; set; }
    }
}
