//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelivMethod
    {
        public int DelID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string DelivMethod1 { get; set; }
        public bool DelActive { get; set; }
    }
}
