//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIUpdateLog
    {
        public int LogID { get; set; }
        public Nullable<System.DateTime> UpdateStart { get; set; }
        public Nullable<System.DateTime> UpdateEnd { get; set; }
        public string CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string ProfileID { get; set; }
        public Nullable<int> CustomerCount { get; set; }
        public Nullable<int> SupplierCount { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public Nullable<int> TaxInvoiceCount { get; set; }
        public Nullable<int> CNCount { get; set; }
        public Nullable<int> SuppInvCount { get; set; }
        public Nullable<int> SuppCNCount { get; set; }
        public Nullable<int> JournalCount { get; set; }
        public Nullable<int> QuotationCount { get; set; }
        public Nullable<int> GLTransCount { get; set; }
        public Nullable<int> AnalysisCodeCount { get; set; }
        public Nullable<System.DateTime> CustomerUpdate { get; set; }
        public Nullable<System.DateTime> SupplierUpdate { get; set; }
        public Nullable<System.DateTime> ItemUpdate { get; set; }
        public Nullable<System.DateTime> TaxInvoiceUpdate { get; set; }
        public Nullable<System.DateTime> CNUpdate { get; set; }
        public Nullable<System.DateTime> SuppInvUpdate { get; set; }
        public Nullable<System.DateTime> SuppCNUpdate { get; set; }
        public Nullable<System.DateTime> JournalUpdate { get; set; }
        public Nullable<System.DateTime> QuoteUpdate { get; set; }
        public Nullable<System.DateTime> GLTransUpdate { get; set; }
        public Nullable<System.DateTime> AnalysisCodeUpdate { get; set; }
        public Nullable<System.DateTime> SalesOrderUpdate { get; set; }
        public Nullable<System.DateTime> CustAdjUpdate { get; set; }
        public Nullable<System.DateTime> SuppAdjUpdate { get; set; }
        public Nullable<System.DateTime> BankUpdate { get; set; }
        public Nullable<System.DateTime> POUpdate { get; set; }
        public Nullable<System.DateTime> SOUpdate { get; set; }
    }
}
