//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocHeader
    {
        public int ID { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public long DocID { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<bool> Inclusive { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public string TaxReference { get; set; }
        public string DocumentNumber { get; set; }
        public string Reference { get; set; }
        public string Message { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Exclusive { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Rounding { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<long> CustSuppID { get; set; }
        public string CustSupName { get; set; }
        public Nullable<long> CustRepID { get; set; }
        public Nullable<System.DateTime> DueDelDate { get; set; }
        public string Status { get; set; }
        public string FromDocument { get; set; }
        public Nullable<long> FromDocumentId { get; set; }
        public Nullable<int> FromDocumentTypeId { get; set; }
        public Nullable<bool> Started { get; set; }
        public Nullable<bool> Complete { get; set; }
        public Nullable<int> CompBy { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string DelAddress1 { get; set; }
        public string DelAddress2 { get; set; }
        public string DelAddress3 { get; set; }
        public string DelAddress4 { get; set; }
        public string DelAddress5 { get; set; }
        public Nullable<long> LinkedJCID { get; set; }
        public Nullable<long> LinkedPSID { get; set; }
        public string SalesRepName { get; set; }
        public string SupplierInvNum { get; set; }
        public string DeliveryBy { get; set; }
        public string InvNum { get; set; }
        public string DNNum { get; set; }
        public Nullable<System.Guid> DocGUID { get; set; }
        public bool Active { get; set; }
        public Nullable<long> LinkedDocID { get; set; }
        public Nullable<long> DefaultPriceListId { get; set; }
        public string DefaultPriceListName { get; set; }
        public Nullable<long> LinkedWOID { get; set; }
        public Nullable<long> SalesRepresentativeId { get; set; }
        public Nullable<decimal> Supplier_ExchangeRate { get; set; }
        public Nullable<long> Supplier_CurrencyId { get; set; }
        public Nullable<decimal> Customer_ExchangeRate { get; set; }
        public Nullable<long> Customer_CurrencyId { get; set; }
        public Nullable<decimal> DocCost { get; set; }
        public Nullable<decimal> DocGP { get; set; }
        public string PostAddress5 { get; set; }
    }
}
