//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForCastHeader
    {
        public int ID { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<bool> Inclusive { get; set; }
        public string Reference { get; set; }
        public string Message { get; set; }
        public Nullable<long> CustSuppID { get; set; }
        public string CustSupName { get; set; }
        public Nullable<long> CustRepID { get; set; }
        public Nullable<System.DateTime> DueDelDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Active { get; set; }
        public string FCastBy { get; set; }
        public string SalesRepName { get; set; }
    }
}
