//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTransaction
    {
        public long TrnID { get; set; }
        public long CompanyID { get; set; }
        public Nullable<long> DocumentID { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public string TransactionType { get; set; }
        public Nullable<long> ItemID { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string Barcode { get; set; }
        public Nullable<long> LotNumberID { get; set; }
        public string LotNumber { get; set; }
        public string Unit { get; set; }
        public Nullable<long> FromID { get; set; }
        public Nullable<long> ToID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> PriceExclusive { get; set; }
        public Nullable<decimal> PriceInclusive { get; set; }
        public Nullable<decimal> AdditionalCosts { get; set; }
        public Nullable<decimal> TotalUnitPriceExclInclAdd { get; set; }
        public Nullable<decimal> TotalUnitPriceInclInclAdd { get; set; }
        public Nullable<decimal> TotalLineValExcl { get; set; }
        public Nullable<decimal> TotalLineValIncl { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> ByRoleID { get; set; }
        public string TransactionReference { get; set; }
        public decimal ExchRate { get; set; }
        public string LotNum { get; set; }
    }
}
