//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTransferHeader
    {
        public int TrfID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<System.DateTime> TrfDate { get; set; }
        public Nullable<long> TrfFromID { get; set; }
        public Nullable<long> TrfToID { get; set; }
        public string TrfBy { get; set; }
        public string TrfStatus { get; set; }
        public string TrfNotes { get; set; }
        public bool TrfStarted { get; set; }
        public bool TrfComplete { get; set; }
        public bool TrfActive { get; set; }
        public Nullable<long> TransferID { get; set; }
        public string TrfReference { get; set; }
        public Nullable<System.DateTime> TrfCompleteDate { get; set; }
        public Nullable<decimal> TrfAddCost { get; set; }
        public string TrfAddCostReason { get; set; }
        public Nullable<bool> TrfAddCostSageUpd { get; set; }
    }
}
