//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsMaster
    {
        public int ItmID { get; set; }
        public long ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryDescript { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> PriceInclusive { get; set; }
        public Nullable<decimal> PriceExclusive { get; set; }
        public Nullable<bool> Physical { get; set; }
        public Nullable<int> TaxTypeIdSales { get; set; }
        public Nullable<decimal> TaxTypeSalesPerc { get; set; }
        public string TaxTypeSalesName { get; set; }
        public Nullable<int> TaxTypeIdPurchase { get; set; }
        public Nullable<decimal> TaxTypePurchPerc { get; set; }
        public string TaxTypePurchName { get; set; }
        public Nullable<decimal> LastCost { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
        public Nullable<decimal> QuantityOnHand { get; set; }
        public string Unit { get; set; }
        public string TextUserField1 { get; set; }
        public string TextUserField2 { get; set; }
        public string TextUserField3 { get; set; }
        public Nullable<decimal> NumericUserField1 { get; set; }
        public Nullable<decimal> NumericUserField2 { get; set; }
        public Nullable<decimal> NumericUserField3 { get; set; }
        public Nullable<bool> YesNoUserField1 { get; set; }
        public Nullable<bool> YesNoUserField2 { get; set; }
        public Nullable<bool> YesNoUserField3 { get; set; }
        public Nullable<int> MajorIndustryCodeId { get; set; }
        public Nullable<decimal> QuantityReserved { get; set; }
        public Nullable<decimal> GPPercentage { get; set; }
        public Nullable<decimal> GPAmount { get; set; }
        public long CompanyID { get; set; }
        public string BarCode { get; set; }
        public Nullable<bool> IsBOMComponent { get; set; }
        public Nullable<bool> IsKitComponent { get; set; }
        public Nullable<bool> IsFinishedGoods { get; set; }
        public Nullable<bool> IsFromBOM { get; set; }
        public Nullable<bool> IsFromKit { get; set; }
        public Nullable<decimal> NettMass { get; set; }
        public Nullable<decimal> TotQOH_MDF { get; set; }
        public Nullable<decimal> TotQPicked { get; set; }
        public Nullable<decimal> TotQJCard { get; set; }
        public decimal ReorderLevel { get; set; }
        public decimal MinReOrderQty { get; set; }
        public bool IsLotTracked { get; set; }
    }
}
