//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCardLine
    {
        public int LineID { get; set; }
        public long JCID { get; set; }
        public long SelectionId { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string BarCode { get; set; }
        public string LotNumber { get; set; }
        public Nullable<int> LineType { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPriceExclusive { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitPriceInclusive { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> Exclusive { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Comments { get; set; }
        public Nullable<long> AnalysisCategoryId1 { get; set; }
        public Nullable<long> AnalysisCategoryId2 { get; set; }
        public Nullable<long> AnalysisCategoryId3 { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string StoreCodeFrom { get; set; }
        public Nullable<System.DateTime> LinePickDate { get; set; }
        public Nullable<bool> Physical { get; set; }
        public Nullable<bool> isKit { get; set; }
        public Nullable<bool> isBundle { get; set; }
        public Nullable<bool> isKitLine { get; set; }
        public Nullable<bool> isBundleLine { get; set; }
        public Nullable<long> SBCALineID { get; set; }
        public Nullable<int> LineTaxTypeID { get; set; }
        public bool PickComplete { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public bool IsLotTracked { get; set; }
        public Nullable<long> ItemTransLineID { get; set; }

        public Nullable<decimal> LinePickQty { get; set; }

        public Nullable<int> LinePickBy { get; set; }
    }
}
