//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitHeader
    {
        public int KitHID { get; set; }
        public string KitCode { get; set; }
        public string kitDescript { get; set; }
        public Nullable<long> FGID { get; set; }
        public string FGCode { get; set; }
        public string FGDescript { get; set; }
        public string StoreCode { get; set; }
        public Nullable<decimal> AddCost01 { get; set; }
        public Nullable<decimal> AddCost02 { get; set; }
        public Nullable<decimal> AddCost03 { get; set; }
        public Nullable<decimal> AddSell01 { get; set; }
        public Nullable<decimal> AddSell02 { get; set; }
        public Nullable<decimal> AddSell03 { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<bool> KitActive { get; set; }
    }
}
