//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickSlipLine
    {
        public int LineID { get; set; }
        public long PSID { get; set; }
        public long SelectionId { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string BarCode { get; set; }
        public string LotNumber { get; set; }
        public Nullable<int> LineType { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public string Comments { get; set; }
        public string StoreCodeFrom { get; set; }
        public Nullable<int> PickBy { get; set; }
        public Nullable<System.DateTime> PickTime { get; set; }
        public Nullable<decimal> PickQty { get; set; }
        public Nullable<bool> PickComplete { get; set; }
        public Nullable<long> SBCALineID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public bool IsLotTracked { get; set; }
        public Nullable<long> ItemTransLineID { get; set; }
    }
}
