//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesMaster
    {
        public int RoleID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string RoleName { get; set; }
        public bool CanReceive { get; set; }
        public bool CanTransfer { get; set; }
        public bool CanViewPickSlips { get; set; }
        public bool CanTrackPickSlips { get; set; }
        public bool CanSalesForecast { get; set; }
        public bool CanViewJobCards { get; set; }
        public bool CanTrackJobCards { get; set; }
        public bool CanSeeFGDemands { get; set; }
        public bool NotifyGRN { get; set; }
        public bool NotifyTransfer { get; set; }
        public bool NotifySOComplete { get; set; }
        public bool NotifyPSMove { get; set; }
        public bool NotifyJCMove { get; set; }
        public bool NotifyProdMove { get; set; }
        public bool CanCreateBomKit { get; set; }
        public bool UseGenericLogin { get; set; }
        public bool NotifyNewSO { get; set; }
        public bool CanInvoice { get; set; }
        public bool IsPicker { get; set; }
        public bool IsJobCards { get; set; }
        public bool IsProduction { get; set; }
        public bool UseEditLotNumbers { get; set; }
        public bool CanStockControl { get; set; }
        public bool CanViewWorksOrders { get; set; }
        public bool CanFillWorksOrders { get; set; }
        public bool CanViewRMD { get; set; }
    }
}
