//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SBMSEntities : DbContext
    {
        public SBMSEntities(string connectionString) : base(connectionString) { }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOMHeader> BOMHeaders { get; set; }
        public virtual DbSet<BOMLine> BOMLines { get; set; }
        public virtual DbSet<DelivMethod> DelivMethods { get; set; }
        public virtual DbSet<DocHeader> DocHeaders { get; set; }
        public virtual DbSet<DocLine> DocLines { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<ForCastHeader> ForCastHeaders { get; set; }
        public virtual DbSet<ForCastLine> ForCastLines { get; set; }
        public virtual DbSet<ItemBarCodeLink> ItemBarCodeLinks { get; set; }
        public virtual DbSet<ItemsMaster> ItemsMasters { get; set; }
        public virtual DbSet<ItemsReorderLevel> ItemsReorderLevels { get; set; }
        public virtual DbSet<ItemStoreLinkMaster> ItemStoreLinkMasters { get; set; }
        public virtual DbSet<ItemTransaction> ItemTransactions { get; set; }
        public virtual DbSet<JobCardLine> JobCardLines { get; set; }
        public virtual DbSet<JobTransaction> JobTransactions { get; set; }
        public virtual DbSet<KitHeader> KitHeaders { get; set; }
        public virtual DbSet<KitLine> KitLines { get; set; }
        public virtual DbSet<LastCallLog> LastCallLogs { get; set; }
        public virtual DbSet<LotTrackingMaster> LotTrackingMasters { get; set; }
        public virtual DbSet<PickSlipLine> PickSlipLines { get; set; }
        public virtual DbSet<PickSlipProcess> PickSlipProcesses { get; set; }
        public virtual DbSet<PickSlipTransaction> PickSlipTransactions { get; set; }
        public virtual DbSet<ProdPlanLine> ProdPlanLines { get; set; }
        public virtual DbSet<ProdTransaction> ProdTransactions { get; set; }
        public virtual DbSet<TempDocLine> TempDocLines { get; set; }
        public virtual DbSet<UsersMaster> UsersMasters { get; set; }
        public virtual DbSet<WorkStation> WorkStations { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<RolesMaster> RolesMasters { get; set; }
        public virtual DbSet<StockCountMaster> StockCountMasters { get; set; }
        public virtual DbSet<BundlesHeader> BundlesHeaders { get; set; }
        public virtual DbSet<BundlesLine> BundlesLines { get; set; }
        public virtual DbSet<JobCardsMaster> JobCardsMasters { get; set; }
        public virtual DbSet<PickingSlipMaster> PickingSlipMasters { get; set; }
        public virtual DbSet<DocHeaderAttachment> DocHeaderAttachments { get; set; }
        public virtual DbSet<AvCostChangeLog> AvCostChangeLogs { get; set; }
        public virtual DbSet<WorksOrderHeader> WorksOrderHeaders { get; set; }
        public virtual DbSet<WorksOrderRMLine> WorksOrderRMLines { get; set; }
        public virtual DbSet<WorksOrderLine> WorksOrderLines { get; set; }
        public virtual DbSet<ReceivingAddCost> ReceivingAddCosts { get; set; }
        public virtual DbSet<AccountsMaster> AccountsMasters { get; set; }
        public virtual DbSet<TaxTypesMaster> TaxTypesMasters { get; set; }
        public virtual DbSet<DynamicReport> DynamicReports { get; set; }
        public virtual DbSet<DIUpdateLog> DIUpdateLogs { get; set; }
        public virtual DbSet<ItemTransferLine> ItemTransferLines { get; set; }
        public virtual DbSet<StockCountLine> StockCountLines { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<ReceivingOutstanding> ReceivingOutstandings { get; set; }
        public virtual DbSet<CompanyMaster> CompanyMasters { get; set; }
        public virtual DbSet<ItemTransferHeader> ItemTransferHeaders { get; set; }
    
        public virtual ObjectResult<GetActiveLotNumbersLinkedToStores_Result> GetActiveLotNumbersLinkedToStores(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveLotNumbersLinkedToStores_Result>("GetActiveLotNumbersLinkedToStores", coIDParameter);
        }
    
        public virtual ObjectResult<getdoclinestest_Result> getdoclinestest(Nullable<long> coID, string itmCode, Nullable<System.DateTime> bfDate)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var itmCodeParameter = itmCode != null ?
                new ObjectParameter("itmCode", itmCode) :
                new ObjectParameter("itmCode", typeof(string));
    
            var bfDateParameter = bfDate.HasValue ?
                new ObjectParameter("bfDate", bfDate) :
                new ObjectParameter("bfDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getdoclinestest_Result>("getdoclinestest", coIDParameter, itmCodeParameter, bfDateParameter);
        }
    
        public virtual ObjectResult<GetFGOpenBalances_Result> GetFGOpenBalances(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFGOpenBalances_Result>("GetFGOpenBalances", coIDParameter);
        }
    
        public virtual ObjectResult<GetJobMovementTransactions_Result> GetJobMovementTransactions(Nullable<long> coID, Nullable<long> jcid)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var jcidParameter = jcid.HasValue ?
                new ObjectParameter("jcid", jcid) :
                new ObjectParameter("jcid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetJobMovementTransactions_Result>("GetJobMovementTransactions", coIDParameter, jcidParameter);
        }
    
        public virtual ObjectResult<GetLinkedStoredFromItem_Result> GetLinkedStoredFromItem(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLinkedStoredFromItem_Result>("GetLinkedStoredFromItem", coIDParameter);
        }
    
        public virtual ObjectResult<GetOneItemFromBarcode_Result> GetOneItemFromBarcode(Nullable<long> coID, string bCode)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var bCodeParameter = bCode != null ?
                new ObjectParameter("bCode", bCode) :
                new ObjectParameter("bCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneItemFromBarcode_Result>("GetOneItemFromBarcode", coIDParameter, bCodeParameter);
        }
    
        public virtual ObjectResult<GetOpeningBalancesAllStores_Result> GetOpeningBalancesAllStores(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOpeningBalancesAllStores_Result>("GetOpeningBalancesAllStores", coIDParameter);
        }
    
        public virtual ObjectResult<GetOpeningBalancesByStore_Result> GetOpeningBalancesByStore(string storeCode, Nullable<long> coID)
        {
            var storeCodeParameter = storeCode != null ?
                new ObjectParameter("storeCode", storeCode) :
                new ObjectParameter("storeCode", typeof(string));
    
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOpeningBalancesByStore_Result>("GetOpeningBalancesByStore", storeCodeParameter, coIDParameter);
        }
    
        public virtual ObjectResult<GetProdPlanMovementTransactions_Result> GetProdPlanMovementTransactions(Nullable<long> coID, Nullable<long> planLineid)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var planLineidParameter = planLineid.HasValue ?
                new ObjectParameter("planLineid", planLineid) :
                new ObjectParameter("planLineid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProdPlanMovementTransactions_Result>("GetProdPlanMovementTransactions", coIDParameter, planLineidParameter);
        }
    
        public virtual ObjectResult<GetQtyOnActiveForecasts_Result> GetQtyOnActiveForecasts(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQtyOnActiveForecasts_Result>("GetQtyOnActiveForecasts", coIDParameter);
        }
    
        public virtual ObjectResult<GetQtyOnActiveJobCards_Result> GetQtyOnActiveJobCards(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQtyOnActiveJobCards_Result>("GetQtyOnActiveJobCards", coIDParameter);
        }
    
        public virtual ObjectResult<GetQtyOnActivePickSlips_Result> GetQtyOnActivePickSlips(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQtyOnActivePickSlips_Result>("GetQtyOnActivePickSlips", coIDParameter);
        }
    
        public virtual ObjectResult<GetQtyOnActivePurchaseOrders_Result> GetQtyOnActivePurchaseOrders(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQtyOnActivePurchaseOrders_Result>("GetQtyOnActivePurchaseOrders", coIDParameter);
        }
    
        public virtual ObjectResult<GetQtyOnActiveWorksOrders_Result> GetQtyOnActiveWorksOrders(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQtyOnActiveWorksOrders_Result>("GetQtyOnActiveWorksOrders", coIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> GetSOPOJCQtyByItemByDate(Nullable<long> coID, string itmCode, Nullable<System.DateTime> bfDate)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var itmCodeParameter = itmCode != null ?
                new ObjectParameter("itmCode", itmCode) :
                new ObjectParameter("itmCode", typeof(string));
    
            var bfDateParameter = bfDate.HasValue ?
                new ObjectParameter("bfDate", bfDate) :
                new ObjectParameter("bfDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetSOPOJCQtyByItemByDate", coIDParameter, itmCodeParameter, bfDateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> GetSOQtyByItemByDate(Nullable<long> coID, string itmCode, Nullable<System.DateTime> bfDate)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var itmCodeParameter = itmCode != null ?
                new ObjectParameter("itmCode", itmCode) :
                new ObjectParameter("itmCode", typeof(string));
    
            var bfDateParameter = bfDate.HasValue ?
                new ObjectParameter("bfDate", bfDate) :
                new ObjectParameter("bfDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetSOQtyByItemByDate", coIDParameter, itmCodeParameter, bfDateParameter);
        }
    
        public virtual int GetTrfOpeningBalances(string storeCode, Nullable<long> coID)
        {
            var storeCodeParameter = storeCode != null ?
                new ObjectParameter("storeCode", storeCode) :
                new ObjectParameter("storeCode", typeof(string));
    
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetTrfOpeningBalances", storeCodeParameter, coIDParameter);
        }
    
        public virtual ObjectResult<GetUserFromCreds_Result> GetUserFromCreds(string username, string pwd)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserFromCreds_Result>("GetUserFromCreds", usernameParameter, pwdParameter);
        }
    
        public virtual ObjectResult<GetItemsQtyOnHandMaster_Result> GetItemsQtyOnHandMaster(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetItemsQtyOnHandMaster_Result>("GetItemsQtyOnHandMaster", coIDParameter);
        }
    
        public virtual ObjectResult<GetAllActiveJobCards_Result> GetAllActiveJobCards(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllActiveJobCards_Result>("GetAllActiveJobCards", coIDParameter);
        }
    
        public virtual ObjectResult<GetAllActivePickingSlips_Result> GetAllActivePickingSlips(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllActivePickingSlips_Result>("GetAllActivePickingSlips", coIDParameter);
        }
    
        public virtual ObjectResult<GetStckCountDetails_Result> GetStckCountDetails(Nullable<long> coID, Nullable<int> countid)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var countidParameter = countid.HasValue ?
                new ObjectParameter("countid", countid) :
                new ObjectParameter("countid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStckCountDetails_Result>("GetStckCountDetails", coIDParameter, countidParameter);
        }
    
        public virtual ObjectResult<GetStockCountList_Result> GetStockCountList(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStockCountList_Result>("GetStockCountList", coIDParameter);
        }
    
        public virtual ObjectResult<GetListOfDocHeadersByType_Result> GetListOfDocHeadersByType(Nullable<long> coID, Nullable<int> docType)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var docTypeParameter = docType.HasValue ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListOfDocHeadersByType_Result>("GetListOfDocHeadersByType", coIDParameter, docTypeParameter);
        }
    
        public virtual ObjectResult<GetPickSlipMovementTransactions_Result> GetPickSlipMovementTransactions(Nullable<long> coID, Nullable<long> psid)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var psidParameter = psid.HasValue ?
                new ObjectParameter("psid", psid) :
                new ObjectParameter("psid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPickSlipMovementTransactions_Result>("GetPickSlipMovementTransactions", coIDParameter, psidParameter);
        }
    
        public virtual ObjectResult<GetOneJobCardFromDocHeaderID_Result> GetOneJobCardFromDocHeaderID(Nullable<long> coID, string docID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var docIDParameter = docID != null ?
                new ObjectParameter("DocID", docID) :
                new ObjectParameter("DocID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneJobCardFromDocHeaderID_Result>("GetOneJobCardFromDocHeaderID", coIDParameter, docIDParameter);
        }
    
        public virtual ObjectResult<GetOneDocHeaderFromDocID_Result> GetOneDocHeaderFromDocID(Nullable<long> coID, string docID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var docIDParameter = docID != null ?
                new ObjectParameter("DocID", docID) :
                new ObjectParameter("DocID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneDocHeaderFromDocID_Result>("GetOneDocHeaderFromDocID", coIDParameter, docIDParameter);
        }
    
        public virtual ObjectResult<GetAllStockLevels_Result> GetAllStockLevels(Nullable<int> coID, string searchTerm)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(int));
    
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStockLevels_Result>("GetAllStockLevels", coIDParameter, searchTermParameter);
        }
    
        public virtual ObjectResult<GetItemLinkedStores_Result> GetItemLinkedStores(Nullable<long> coID, Nullable<long> itmID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var itmIDParameter = itmID.HasValue ?
                new ObjectParameter("itmID", itmID) :
                new ObjectParameter("itmID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetItemLinkedStores_Result>("GetItemLinkedStores", coIDParameter, itmIDParameter);
        }
    
        public virtual ObjectResult<GetItemTransferHistoryByDate_Result> GetItemTransferHistoryByDate(Nullable<long> coID, Nullable<System.DateTime> frmdt, Nullable<System.DateTime> todt)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var frmdtParameter = frmdt.HasValue ?
                new ObjectParameter("frmdt", frmdt) :
                new ObjectParameter("frmdt", typeof(System.DateTime));
    
            var todtParameter = todt.HasValue ?
                new ObjectParameter("todt", todt) :
                new ObjectParameter("todt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetItemTransferHistoryByDate_Result>("GetItemTransferHistoryByDate", coIDParameter, frmdtParameter, todtParameter);
        }
    
        public virtual ObjectResult<GetFGDemmandsAll_Result> GetFGDemmandsAll(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFGDemmandsAll_Result>("GetFGDemmandsAll", coIDParameter);
        }
    
        public virtual ObjectResult<GetKitLinesFromKitCode_Result> GetKitLinesFromKitCode(string bomCode, Nullable<long> coid)
        {
            var bomCodeParameter = bomCode != null ?
                new ObjectParameter("bomCode", bomCode) :
                new ObjectParameter("bomCode", typeof(string));
    
            var coidParameter = coid.HasValue ?
                new ObjectParameter("coid", coid) :
                new ObjectParameter("coid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetKitLinesFromKitCode_Result>("GetKitLinesFromKitCode", bomCodeParameter, coidParameter);
        }
    
        public virtual ObjectResult<GetKitLinesFromKitHeaderID_Result> GetKitLinesFromKitHeaderID(Nullable<int> kitHID, Nullable<long> coid)
        {
            var kitHIDParameter = kitHID.HasValue ?
                new ObjectParameter("KitHID", kitHID) :
                new ObjectParameter("KitHID", typeof(int));
    
            var coidParameter = coid.HasValue ?
                new ObjectParameter("coid", coid) :
                new ObjectParameter("coid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetKitLinesFromKitHeaderID_Result>("GetKitLinesFromKitHeaderID", kitHIDParameter, coidParameter);
        }
    
        public virtual ObjectResult<GetOnePickingSlipFromDocHeaderID_Result> GetOnePickingSlipFromDocHeaderID(Nullable<long> coID, string docID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var docIDParameter = docID != null ?
                new ObjectParameter("DocID", docID) :
                new ObjectParameter("DocID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOnePickingSlipFromDocHeaderID_Result>("GetOnePickingSlipFromDocHeaderID", coIDParameter, docIDParameter);
        }
    
        public virtual ObjectResult<GetProdRMDemands_Result> GetProdRMDemands(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProdRMDemands_Result>("GetProdRMDemands", coIDParameter);
        }
    
        public virtual ObjectResult<GetBOMLinesFromBomHeaderID_Result> GetBOMLinesFromBomHeaderID(Nullable<int> bomHID, Nullable<long> coid)
        {
            var bomHIDParameter = bomHID.HasValue ?
                new ObjectParameter("bomHID", bomHID) :
                new ObjectParameter("bomHID", typeof(int));
    
            var coidParameter = coid.HasValue ?
                new ObjectParameter("coid", coid) :
                new ObjectParameter("coid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBOMLinesFromBomHeaderID_Result>("GetBOMLinesFromBomHeaderID", bomHIDParameter, coidParameter);
        }
    
        public virtual ObjectResult<GetBOMLinesFromBomCode_Result> GetBOMLinesFromBomCode(string bomCode, Nullable<long> coid)
        {
            var bomCodeParameter = bomCode != null ?
                new ObjectParameter("bomCode", bomCode) :
                new ObjectParameter("bomCode", typeof(string));
    
            var coidParameter = coid.HasValue ?
                new ObjectParameter("coid", coid) :
                new ObjectParameter("coid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBOMLinesFromBomCode_Result>("GetBOMLinesFromBomCode", bomCodeParameter, coidParameter);
        }
    
        public virtual ObjectResult<GetKitLinesFromKitHeaderID_Result1> GetKitLinesFromKitHeaderID1(Nullable<int> kitHID, Nullable<long> coid)
        {
            var kitHIDParameter = kitHID.HasValue ?
                new ObjectParameter("KitHID", kitHID) :
                new ObjectParameter("KitHID", typeof(int));
    
            var coidParameter = coid.HasValue ?
                new ObjectParameter("coid", coid) :
                new ObjectParameter("coid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetKitLinesFromKitHeaderID_Result1>("GetKitLinesFromKitHeaderID1", kitHIDParameter, coidParameter);
        }
    
        public virtual ObjectResult<GetAllStockLevelsByLotNumber_Result> GetAllStockLevelsByLotNumber(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStockLevelsByLotNumber_Result>("GetAllStockLevelsByLotNumber", coIDParameter);
        }
    
        public virtual ObjectResult<GetAllStockLevelsByLotNumber_ExclStore_Result> GetAllStockLevelsByLotNumber_ExclStore(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStockLevelsByLotNumber_ExclStore_Result>("GetAllStockLevelsByLotNumber_ExclStore", coIDParameter);
        }
    
        public virtual ObjectResult<GetItemDemmandsAll_Result> GetItemDemmandsAll(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetItemDemmandsAll_Result>("GetItemDemmandsAll", coIDParameter);
        }
    
        public virtual ObjectResult<GetOpeningBalancesAllStores_No_LotNum_Result> GetOpeningBalancesAllStores_No_LotNum(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOpeningBalancesAllStores_No_LotNum_Result>("GetOpeningBalancesAllStores_No_LotNum", coIDParameter);
        }
    
        public virtual ObjectResult<GetValidateBarcode_Result> GetValidateBarcode(Nullable<long> coID, string itmCode)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var itmCodeParameter = itmCode != null ?
                new ObjectParameter("itmCode", itmCode) :
                new ObjectParameter("itmCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetValidateBarcode_Result>("GetValidateBarcode", coIDParameter, itmCodeParameter);
        }
    
        public virtual ObjectResult<sp_DeliverySchedule_Result> sp_DeliverySchedule(Nullable<long> coID)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DeliverySchedule_Result>("sp_DeliverySchedule", coIDParameter);
        }
    
        public virtual ObjectResult<sp_GetItemsForDisplay_Result> sp_GetItemsForDisplay(Nullable<long> companyID, string searchText, Nullable<bool> excludeZeroQty)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            var excludeZeroQtyParameter = excludeZeroQty.HasValue ?
                new ObjectParameter("ExcludeZeroQty", excludeZeroQty) :
                new ObjectParameter("ExcludeZeroQty", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetItemsForDisplay_Result>("sp_GetItemsForDisplay", companyIDParameter, searchTextParameter, excludeZeroQtyParameter);
        }
    
        public virtual ObjectResult<GetStckCountVariances_Result> GetStckCountVariances(Nullable<long> coID, Nullable<int> countid)
        {
            var coIDParameter = coID.HasValue ?
                new ObjectParameter("CoID", coID) :
                new ObjectParameter("CoID", typeof(long));
    
            var countidParameter = countid.HasValue ?
                new ObjectParameter("countid", countid) :
                new ObjectParameter("countid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStckCountVariances_Result>("GetStckCountVariances", coIDParameter, countidParameter);
        }
    }
}
