//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int StoreID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string StoreCode { get; set; }
        public string StoreDescript { get; set; }
        public Nullable<bool> StoreActive { get; set; }
        public bool StorePerm { get; set; }
        public bool AllowPicking { get; set; }
        public bool AllowReceiving { get; set; }
        public bool IsRejectStore { get; set; }
        public bool IsWip { get; set; }
    }
}
