//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxTypesMaster
    {
        public int TaxID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> TaxTypeID { get; set; }
        public Nullable<decimal> TaxPerc { get; set; }
        public string TaxTypeName { get; set; }
    }
}
