//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkStation
    {
        public int WSID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string WSName { get; set; }
        public bool WSActive { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<bool> IsWIP { get; set; }
    }
}
