//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksOrderLine
    {
        public int LineID { get; set; }
        public long WOID { get; set; }
        public long SelectionId { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> LineType { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DueDelDate { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LotNumber { get; set; }
        public Nullable<bool> Complete { get; set; }
        public Nullable<int> CompleteBy { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<bool> SageUpdated { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public decimal UseQty { get; set; }
        public decimal ScrapQty { get; set; }
        public decimal RejectQty { get; set; }
        public Nullable<int> ToStoreID { get; set; }
        public Nullable<System.DateTime> ToStoreDate { get; set; }
        public Nullable<int> ToStoreBy { get; set; }
        public bool IsLotTracked { get; set; }
        public Nullable<decimal> OrderedQty { get; set; }
    }
}
