//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksOrderHeader
    {
        public int ID { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<System.DateTime> WOrderDate { get; set; }
        public string Reference { get; set; }
        public string Message { get; set; }
        public string CustSupName { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Active { get; set; }
        public string WOrderBy { get; set; }
        public Nullable<System.DateTime> WOrderCloseOffDate { get; set; }
        public string LinkedDocumentNum { get; set; }
        public int WONum { get; set; }
        public string WOrderCloseBy { get; set; }
    }
}
