using iTextSharp.text;
using iTextSharp.text.pdf;
using System;

namespace SBMS.Classes
{
    public class PDFFooter : PdfPageEventHelper
    {
        // This is the contentbyte object of the writer
        PdfContentByte cb;
        // we will put the final number of pages in a template
        PdfTemplate template;
        //SqlCommands sqlc = new SqlCommands();
        BaseFont bf = null;
        // write on top of document       
        public override void OnOpenDocument(PdfWriter writer, Document document)
        {
            bf = BaseFont.CreateFont(BaseFont.TIMES_ROMAN, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
            cb = writer.DirectContent;
            template = cb.CreateTemplate(50, 50);
        }

        // write on start of each page
        public override void OnStartPage(PdfWriter writer, Document document)
        {
            base.OnStartPage(writer, document);
        }

        // write on end of each page
        public override void OnEndPage(PdfWriter writer, Document document)
        {
            base.OnEndPage(writer, document);
            int currentPage = writer.PageNumber;
            string text = "Completed By: _______________________________";
            string text1 = "Date: ________________________________";
            string text2 = "Checked: ________________________________";

            //string text3 = "________________________________________________________________________________________________________";
            string textpg = $"Page {currentPage}";
            string textfoot = $"Generated by mydatafusion.online";
            string textPrintDate = $"Printed:" + DateTime.Now.ToString();
            Rectangle pageSize = document.PageSize;
            cb.SetRGBColorFill(100, 100, 100);
            cb.BeginText();
            cb.SetFontAndSize(bf, 8);
            
            cb.ShowTextAligned(PdfContentByte.ALIGN_LEFT, text, (25), 50, 0);
            cb.ShowTextAligned(PdfContentByte.ALIGN_RIGHT, text1, (pageSize.Width - 50f), 50, 0);
            cb.ShowTextAligned(PdfContentByte.ALIGN_CENTER, text2, (pageSize.Width / 2), 50, 0);

            //cb.ShowTextAligned(PdfContentByte.ALIGN_CENTER, text3, (pageSize.Width / 2), 45, 0);
            
            cb.ShowTextAligned(PdfContentByte.ALIGN_RIGHT, textpg, (pageSize.Width -50f), 25, 0);
            cb.ShowTextAligned(PdfContentByte.ALIGN_CENTER, textPrintDate, (pageSize.Width / 2), 25, 0);
            cb.ShowTextAligned(PdfContentByte.ALIGN_LEFT, textfoot, (25), 25, 0);
            cb.EndText();
        }

        //write on close of document
        public override void OnCloseDocument(PdfWriter writer, Document document)
        {
            //base.OnCloseDocument(writer, document);

            // Calculate total number of pages
            int totalPages = writer.PageNumber - 1;

            // Create a PdfContentByte object
            PdfContentByte cb = writer.DirectContent;

            // Move to the correct position
            cb.BeginText();
            cb.SetFontAndSize(BaseFont.CreateFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED), 8);
            cb.SetTextMatrix(0, 0);
            cb.ShowTextAligned(PdfContentByte.ALIGN_RIGHT, totalPages.ToString(), 25, 25, 0);
            cb.EndText();
        }
    }
}
