//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS
{
    public partial class LotBackfill
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Button btnPreview;
        protected global::System.Web.UI.WebControls.TextBox txtConfirm;
        protected global::System.Web.UI.WebControls.Button btnApply;
        protected global::System.Web.UI.WebControls.Literal lblStatus;
        protected global::System.Web.UI.WebControls.GridView gvPlan;
        // OldLot is bound declaratively in the .aspx - no designer field needed.
    }
}
