//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBMS
{
    public partial class Traceability
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// lbtnHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnHome;

        /// <summary>
        /// lbtnExcel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnExcel;

        /// <summary>
        /// lbtnLogOut control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnLogOut;

        /// <summary>
        /// imgCoImg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgCoImg;

        /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// lbtnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnSearch;

        /// <summary>
        /// lblErr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErr;

        /// <summary>
        /// pnlSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSummary;

        /// <summary>
        /// litSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSummary;

        /// <summary>
        /// pnlUnits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUnits;

        /// <summary>
        /// GridUnits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridUnits;

        /// <summary>
        /// pnlHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlHistory;

        /// <summary>
        /// GridHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridHistory;

        /// <summary>
        /// pnlCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCustomers;

        /// <summary>
        /// GridCustomers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridCustomers;
    }
}
